packages:
  - "."
  - "server"

allowBuilds:
  '@parcel/watcher': true
  '@sentry/node-cpu-profiler': true
  bcrypt: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  nodent-runtime: true
  unrs-resolver: true
