packages:
  - "."
  - "server"

allowBuilds:
  - "@parcel/watcher"
  - "bcrypt"
  - "core-js"
  - "esbuild"
  - "nodent-runtime"
  - "unrs-resolver"
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/node-cpu-profiler"
  - "msgpackr-extract"
