packages:
  - "."
  - "server"

allowBuilds:
  '0': '@parcel/watcher'
  '1': bcrypt
  '2': core-js
  '3': esbuild
  '4': nodent-runtime
  '5': unrs-resolver
  '6': '@sentry-internal/node-cpu-profiler'
  '7': '@sentry/node-cpu-profiler'
  '8': msgpackr-extract
  '@parcel/watcher': set this to true or false
  bcrypt: set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  nodent-runtime: set this to true or false
  unrs-resolver: set this to true or false
