services:
  - type: web
    name: printshop-server
    env: node
    plan: free
    buildCommand: "cd server && npm install"
    startCommand: "node server/server.js"
    envVars:
      - key: NODE_ENV
        value: production
